CREATE USER MANAGER IDENTIFIED BY "DuocUc..2025"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DATA;
GRANT CONNECT TO MANAGER;
GRANT RESOURCE TO MANAGER;
ALTER USER MANAGER DEFAULT ROLE CONNECT,RESOURCE;

CREATE ROLE ROL_COMUN;

GRANT SELECT ON MANAGER.CREDITO TO ROL_COMUN;
GRANT SELECT ON MANAGER.MOVIMIENTO TO ROL_COMUN;
GRANT SELECT ON MANAGER.PRODUCTO_INVERSION TO ROL_COMUN;
GRANT SELECT ON MANAGER.PROVINCIA TO ROL_COMUN;

GRANT INSERT, UPDATE, DELETE ON MANAGER.CREDITO_CLIENTE TO ROL_COMUN;
GRANT INSERT, UPDATE, DELETE ON MANAGER.PRODUCTO_INVERSION_CLIENTE TO ROL_COMUN;
GRANT INSERT, UPDATE, DELETE ON MANAGER.CUOTA_CREDITO_CLIENTE TO ROL_COMUN;

--COMENTARIO DE UNA LINEA

/*COMENTARIO
DE
MULTIPLES LINEAS
*/

CREATE PROFILE PERF_USUARIO LIMIT 
SESSIONS_PER_USER 3 -- NUMEROS
IDLE_TIME 15 --MINUTOS
FAILED_LOGIN_ATTEMPTS 15 --NUMEROS
PASSWORD_LIFE_TIME 50; --DIAS


CREATE USER EMPLEADO IDENTIFIED BY "DuocUc..2025"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
PROFILE PERF_USUARIO
QUOTA UNLIMITED ON DATA;
GRANT CREATE SESSION TO EMPLEADO;
GRANT ROL_COMUN TO EMPLEADO;
ALTER USER EMPLEADO DEFAULT ROLE ROL_COMUN;

SELECT * FROM DBA_USERS;
--SI SE ME OLVIDO ASIGNAR PERFIL -> ALTER USER nombre.usuario profile nombre_perfil;
CREATE PUBLIC SYNONYM PAVITO
FOR HR.COUNTRIES;

CREATE SYNONYM EMPLEADO.VIC
FOR HR.EMPLOYEES;

GRANT SELECT ON HR.EMPLOYEES TO VIC;

CREATE PUBLIC SYNONYM CREDITO_CLIENTE
FOR MANAGER.CREDITO_CLIENTE;

CREATE PUBLIC SYNONYM PRODUCTO_INVERSION_CLIENTE
FOR MANAGER.PRODUCTO_INVERSION_CLIENTE;

CREATE PUBLIC SYNONYM CUOTA_CREDITO_CLIENTE
FOR MANAGER.CUOTA_CREDITO_CLIENTE;
